# Applied Computational Statistics (ACS)

## SW2

Submit your answers <b>individually</b>.

In [157]:
import numpy as np

atol = 0.01

---

### Dungeons & Dragons Revisited

This seatwork presents a collection of D&D related questions. Hopefully, answering them inspires you to play D&D.

Click [`here`](https://media.wizards.com/2018/dnd/downloads/DnD_BasicRules_2018.pdf) to read the free basic rules for 5th Edition D&D. (not required)

Some notes:

1. When using a Monte Carlo approach, make sure to set your sample/simulation size to be large enough such that your results are stable.


2. There are many possible ways to simulate the problems below. Certain methods will be more efficient and less samples to converge. Try to be as efficient as possible, otherwise your solution may not converge to the accepted tolerance (absolute tolerance of 0.01).


3. If your implementation takes more than a minute to run, you will not recieve points for the question!

#### Q1.

Your character, a level 1 fighter, attacks a goblin with a longsword. 

An attack will hit if your <b><i>Attack Roll</b></i> is equal to or exceeds the target's <b><i>Armor Class (AC)</b></i>.

You make an attack roll by rolling a d20 and adding your <b><i>Ability Modifier</b></i> (Strength in this case) and <b><i>Proficiency Bonus</b></i>.

Suppose that you have a strength modifier of +3, a proficiency bonus of +2, and that the goblin's AC is 12.

Calculate the probability that your attack will hit the goblin.

<i>Note: The ability modifier used for a melee weapon attack is Strength, and the ability modifier used for a ranged weapon attack is Dexterity. Weapons that have the finesse or thrown property break this rule.</i>

In [158]:
def p_hit(str_mod=0, prof_bonus=0, target_ac=10):
    
    p_hit = 0
    
    # YOUR CODE HERE
    np.random.seed(1)
    simnum = 1000000
    rolls = []
    d20 = list(range(1,21))
    for i in range(0,simnum):
        roll = np.random.choice(d20)
        if roll >= target_ac - str_mod - prof_bonus:
            rolls.append(roll)

    p_hit = len(rolls)/simnum    
    
    return p_hit

print('Probability of a Hit:', p_hit(str_mod=3, prof_bonus=2, target_ac=12))

Probability of a Hit: 0.700258


In [159]:
# events
# A1 = Hit goblin       d20 + Ab Mod + Prof Bon >= AC
# A2 = Miss Goblin      d20 + Ab Mod + Prof Bon < AC

# Sample Space includes modifiers and bonus:
# {6-25}
# Misses - 6/20
# Hits - 14/20 or 70%

In [160]:
# another sol
prof_bonus = 2
str_mod = 3
target_ac = 12
rolls = np.arange(1,21) + prof_bonus + str_mod
(rolls >= target_ac).sum() / len(rolls)


0.7

In [161]:
# Hidden Test 1


In [162]:
# Hidden Test 2, 3, 4


#### Q2.

Your character, a level 5 wizard, casts the <b><i>Fireball</b></i> spell which deals 8d6 fire damage in a 20-foot-radius sphere. 

Unfortunately, one of your party members was caught in the blast!

Calculate the 90th percentile of the potential damage dealt to your (former) friend.

<i>Note for the experienced player: Assume that your friend fails their dexterity saving throw and takes full damage.</i>

In [163]:
def fireball_dmg(ptile=0.5):
    
    fireball_dmg_ptile = 0
    np.random.seed(1)
    rolls = []
    for i in range(100000):
        roll = np.random.choice([1,2,3,4,5,6], size=8)
        rolls.append(sum(roll))
    rolls = np.array(rolls)

    fireball_dmg_ptile = np.quantile(rolls, ptile)
    
    return fireball_dmg_ptile

print('90%-ile of Fireball Damage:', fireball_dmg(ptile=0.9))

90%-ile of Fireball Damage: 34.0


In [164]:
# Hidden Test 1


In [165]:
# Hidden Test 2, 3, 4


#### Q3.

Your character has just been reduced to 0 <b><i>Hit Points (HP)</b></i> (because of a fireball) and is now dying. They must now make several <b><i>Death Saving Throws</b></i> to determine their fate.

Death saving throws are rolled every turn until you get three successes or three failures.

To make a death saving throw, simply roll a d20. If the roll is 10 or higher, you succeed. Otherwise, you fail.

On your third success, you become stable. On your third failure, you die.

If you roll a 1, it counts as two failures. 

If you roll a 20, you regain 1 hit point. In which case, you regain consciousness and can fight once more!

Calculate the probability that your character dies.

In [166]:
def p_death():
    p_death = 0
    simnum = 1000
    d20 = list(range(1,21))
    np.random.seed(1)
    li = []
    for _ in range(1000000):
        succeed = False
        count_suc = 0
        count_fail = 0
        for i in range(100000000):
            roll = np.random.choice(d20)
            if 10 <= roll <= 19:
                count_suc += 1
            elif roll == 1:
                count_fail += 2
            elif roll == 20:
                succeed = True
                break
            else:
                count_fail += 1
            if count_suc == 3:
                succeed = True
                break
            if count_fail >= 3:
                succeed = False
                break 
        li.append(succeed)
    p_death = len([i for i in li if i is False])/len(li)
    return p_death

print('Probability that you die:', p_death())

Probability that you die: 0.404409


### NEVERMIND THE PORTIONS BELOW JUST MAKING ALTERNATIVE SOLS

In [167]:
trials = 10
throws = 5
np.random.seed(1)
rolls = np.random.randint(1,21, size=(trials, throws))
rolls

array([[ 6, 12, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 14,  7],
       [19,  6, 19, 12, 11],
       [15, 19,  5, 10, 18],
       [ 1, 14, 10, 10,  8],
       [ 2,  1, 18,  9, 14],
       [20, 16, 11,  9,  8],
       [ 4,  7, 18,  4,  5],
       [18, 12, 13, 17, 14]])

In [168]:
succ = np.zeros(shape=(trials, throws))
fails = np.zeros(shape=(trials, throws))

succ

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [169]:
fails[rolls<10] = 1
succ[rolls >= 10] = 1
succ[rolls == 20] = 3
fails[rolls == 1] = 2

succ

array([[0., 1., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [3., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [170]:
fails

array([[1., 0., 0., 1., 0.],
       [0., 1., 0., 2., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [2., 0., 0., 0., 1.],
       [1., 2., 0., 1., 0.],
       [0., 0., 0., 1., 1.],
       [1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0.]])

### END OF ALTERNATIVE SOLS TRIALS

In [171]:
# Hidden Test 1


#### Q4.

Your character, a ranger, uses a longbow to fire an arrow at a dragon. 

Suppose that you have a Dex modifier of +5, a proficiency bonus of +4, and that the dragon's AC is 20.

In addition, one of your companions is distracting the dragon granting you <b><i>Advantage</b></i>. When making the roll, you may roll the d20 twice and take the higher result.

Calculate the probability that your arrow will hit the dragon.

Implement advantage as a boolean in the function below (i.e. you should still get the correct probability if the flag is set to False).

<i>Note: The ability modifier used for a melee weapon attack is Strength, and the ability modifier used for a ranged weapon attack is Dexterity. Weapons that have the finesse or thrown property break this rule.</i>

In [182]:
def p_hit_2(abl_mod=0, prof_bonus=0, target_ac=10, advantage=False):
    np.random.seed(2)
    
    simnum = 2000000
    minimum = target_ac - abl_mod - prof_bonus
    li = []
    
    k = 2 if advantage is True else 1
    
    for _ in range(simnum):
        roll = np.random.choice(np.arange(1,21), k)
        li.append(max(roll))
    
    li = np.array(li)
    p_hit = len(li[li>=minimum]) / simnum
    
    return p_hit

print('Probability of a Hit:', p_hit_2(abl_mod=5, prof_bonus=4, target_ac=20, advantage=True))

Probability of a Hit: 0.7498535


In [173]:
# Dex = 5
# p_bon = 4

# Dex + p_bon + roll >= 20

# p(roll>=11) 
# = 1-p(roll<11)
# = 1 - 1/2 * 1/2
# = 1-1/4 = 0.75 or 75% for advantage = false

# = 1 - 1/2 or 0.5 for advantage = true


In [174]:
# Hidden Test 1


In [175]:
# Hidden Test 2, 3, 4


#### Q5.

Your character, a level 5 wizard, casts the <b><i>Fireball</b></i> spell which deals 8d6 fire damage in a 20-foot-radius sphere. 

Once again, your companion was caught in the blast! This time however, they expected this to happen and were not caught unprepared. 

They must now make a <b><i>Dexterity Saving Throw</b></i> against your <b><i>Spell Save DC</b></i> (difficulty class). 

If he succeeds (rolls equal to or above the DC), he only takes half damage. Otherwise, he takes full damage.

To make a saving throw, roll a d20 and add the appropriate modifiers.

Suppose that your spell save DC is a 15 and that your companion has a +6 total to their Dex saving throw.

Calculate the expected amount of damage done to your companion.

In [176]:
def fireball_dmg_expected(spell_dc=10, dex_saving_mod=0):
    np.random.seed(1)
    n = 1000000
    fireball_sim = []
    
    for i in range(n):
        roll_1d20 = np.random.randint(low=1, high=21)
        roll_8d6 = np.random.randint(low=1, high=7, size=8).sum()
        
        if roll_1d20 + dex_saving_mod >= spell_dc:
            fireball_sim.append(roll_8d6/2)
        else:
            fireball_sim.append(roll_8d6)
    fireball_dmg_expected = np.mean(fireball_sim)
    
    return fireball_dmg_expected

print('Expected Fireball Damage:', fireball_dmg_expected(spell_dc=15, dex_saving_mod=6))

Expected Fireball Damage: 19.594123


In [177]:
## Hidden Test 1


In [178]:
# Hidden Test 2, 3, 4
