# Mathematics for Data Science

## Midterm Exam (Part 1) - Coding Problem

This notebook should be submitted <b><u>individually</u></b>.   

Name: John Gacal

<b><u>Read the instructions and questions carefully.</u></b>

Do <b><u>NOT</u></b> import any other libraries aside from those below.

In [5]:
import numpy as np

---

## Inverting Matrices (10 pts.)

### Q1. Determinant of an $n \times n$ Matrix (5 pts.)

Create a python function called `determinant` that can calculate the determinant of an $n \times n$ matrix.

Use it to calculate the determinant of the following matrices:

\begin{equation}
    A = \begin{bmatrix}
    8 & 5 & 3\\
    -3 & 10 & 2\\
    2 & 0 & -4\\
    \end{bmatrix}
\end{equation}

\begin{equation}
    B = \begin{bmatrix}
    1 & -3 & 5 & -7\\
   -2 & 4 & -6 & 8\\
    12 & 11 & 10 & 9\\
    -13 & -14 & -15 & -16
    \end{bmatrix}
\end{equation}

<b>Notes:</b> 

1. For this problem, the only `numpy` functions you may use are: `np.array`, `np.matrix`, and `np.delete` (i.e. do <b><u>NOT</b></u> use `np.ndarray.dot`, `np.matmul`, etc.).


2. For simplicity, you may assume that the input dimensions are valid.


3. You can use `np.linalg.det` to check your answer.

In [21]:
# Your code here

def determinant(A):
    if A.shape == (2, 2):
        return A[0, 0]*A[1, 1] - A[1, 0]*A[0, 1]
    elif A.shape == (1,1):
        return A[0][0]
    
    else:
        i = 0
        rolling_sum = 0
        for j in range(A.shape[1]):
            rolling_sum += ((-1)**(i+j+2))*A[i, j]*determinant(np.delete(A, j, 1)[i+1:])
        return rolling_sum
            
A = np.array([[8, 5, 3], [-3, 10, 2], [2, 0, 4]])

print(determinant(A))
print(np.linalg.det(A))

B = np.array([[1, -3, 5, -7], [-2, 4, -6, 8], [12, 11, 10, 9], [-13, -14, -15, -16]])

print(determinant(B))
print(np.linalg.det(B))



340
340.0000000000001
800
799.9999999999999


### Q2. Method of Cofactors (5 pts.)

Create a python function called `adjoint` that can calculate the adjoint of an $n \times n$ matrix. 

Using the <b><i>method of cofactors</b></i>, calculate the inverse of the following matrices:

\begin{equation}
    A = \begin{bmatrix}
    8 & 5 & 3\\
    -3 & 10 & 2\\
    2 & 0 & -4\\
    \end{bmatrix}
\end{equation}

\begin{equation}
    B = \begin{bmatrix}
    1 & -3 & 5 & -7\\
   -2 & 4 & -6 & 8\\
    12 & 11 & 10 & 9\\
    -13 & -14 & -15 & -16
    \end{bmatrix}
\end{equation}

<b>Notes:</b> 

1. For this problem, the only `numpy` functions you may use are: `np.array`, `np.matrix`, `np.zeros`, `np.transpose / np.ndarray.T`, and `np.delete` (i.e. do <b><u>NOT</b></u> use `np.ndarray.dot`, `np.matmul`, etc.).


2. For simplicity, you may assume that the input dimensions are valid.


3. You can use `np.linalg.inv` to check your answer.

In [22]:
def adjoint(A):
    C = np.zeros(shape=(A.shape[0], A.shape[1]))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            C[i, j] = ((-1)**(i+j+2))*determinant(np.delete(np.delete(A, i, 0), j, 1))
    return np.transpose(C)

print(adjoint(A)/determinant(A))
print(np.linalg.inv(A))

print(adjoint(B)/determinant(B))
print(np.linalg.inv(B))

[[ 0.11764706 -0.05882353 -0.05882353]
 [ 0.04705882  0.07647059 -0.07352941]
 [-0.05882353  0.02941176  0.27941176]]
[[ 0.11764706 -0.05882353 -0.05882353]
 [ 0.04705882  0.07647059 -0.07352941]
 [-0.05882353  0.02941176  0.27941176]]
[[-0.75  -0.625  0.15   0.1  ]
 [ 1.     0.875  0.16   0.09 ]
 [ 0.25   0.125 -0.13  -0.12 ]
 [-0.5   -0.375 -0.14  -0.11 ]]
[[-0.75  -0.625  0.15   0.1  ]
 [ 1.     0.875  0.16   0.09 ]
 [ 0.25   0.125 -0.13  -0.12 ]
 [-0.5   -0.375 -0.14  -0.11 ]]
