In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
## Helper function: don't mind this
def randint(size):
    return np.random.randint(0, 20, size)

# <span style="color:#FF6666;font-size:28pt">  Shapes </span>
    
## <span style="color:#33FFBB;font-size:16pt"> Identify the shape

In [ ]:
arr1 = np.array([1, 2, 3])
#arr1.shape

In [2]:
arr2 = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                ])
arr2.shape

(2, 3)

In [ ]:
arr2b = np.array([
                    [1, 2, 3],
                    [4, 5, 6, 7, 8]
                ])
# arr2b.shape

In [3]:
arr3 = np.array([
                    [
                        [ 1, 2, 3],
                        [ 4, 5, 6],
                        [ 7, 8, 9],
                        [10,11,12]
                    ],
                    [
                        [13, 14, 15],
                        [16, 17, 18],
                        [19, 20, 21],
                        [22, 23, 24]
                    ]
                ])
arr3.shape

(2, 4, 3)

In [ ]:
arr3 = np.array([
                    [
                        [ 1, 2, 3],
                        [ 4, 5, 6],
                        [ 7, 8, 9],
                        [10,11,12]
                    ],
                    [
                        [13, 14, 15],
                        [16, 17, 18],
                        [19, 20, 21]
                    ]
                ])
#arr3.shape

## <span style="color:#33FFBB;font-size:16pt"> Manipulate the shape

**By adding a new axis**

**By transposing**

**By using reshape**

**`-1` when using reshape**

## <span style="color:#33FFBB;font-size:16pt"> Compatible shapes and broadcasting

### Obviously compatible

In [ ]:
a = np.ones((2, 4, 5))
b = randint((2, 4, 5))
display(a, b)

### One axis = 1

In [ ]:
a = np.ones((2, 4, 5))
b = randint((2, 1, 5))
display(a, b)

### 1D arrays

In [ ]:
a = np.ones((5))
b = randint((2, 1, 5))
display(a, b)

# <span style="color:#FF6666;font-size:28pt"> Accessing elements

In [4]:
arr = np.arange(70).reshape(7, -1)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

## <span style="color:#33FFBB;font-size:16pt"> Slicing </span>
### Get a single row/column

In [8]:
# Get the row that starts with 30
arr[3,]

# Get the column [4, 14, ..., 54]



array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

### Get a contiguous block

In [12]:
# Get the the rows of 20s 30s 40s
arr[2:5,-3:]

# Get...
# [[27, 28, 29], 
#  [37, 38, 39],
#  [47, 48, 49]]



array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

### Get skipping blocks

In [13]:
# Get the even numbers from rows that start with 0, 30, 60.


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

### Get specific rows

In [16]:
# Get the rows 10, 20, and 50

arr[[1,2,5], :]
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

### Get specific elements

In [17]:
# Get the numbers 11, 27, and 53

arr[[1,2,5],[1,7,3]]

array([11, 27, 53])

In [18]:
arr3 #get 4 and 21

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [19]:
#4 is (0,1,0)
#21 is (1,2,2)

arr3[[0,1], [1,2], [0,2]]

array([ 4, 21])

## <span style="color:#33FFBB;font-size:16pt"> Masking

**Make a mask that gets all numbers divisible by 7.**

In [20]:
mask = arr[(arr % 7 == 0)]
mask

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

**Apply the mask to the array to get all numberes divisible by 7**

## <span style="color:#33FFBB;font-size:16pt"> Masking with np.where

**Get mask using np.where**

In [25]:
wer = np.where(arr % 7 == 0) #returns indices where it is true
wer

(array([0, 0, 1, 2, 2, 3, 4, 4, 5, 6], dtype=int64),
 array([0, 7, 4, 1, 8, 5, 2, 9, 6, 3], dtype=int64))

In [24]:
arr[wer]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

**Change all the lucky numbers divisible by 7 to 0**

In [28]:
arr_div7 = arr.copy()
arr_div7[wer] = 0
arr_div7

array([[ 0,  1,  2,  3,  4,  5,  6,  0,  8,  9],
       [10, 11, 12, 13,  0, 15, 16, 17, 18, 19],
       [20,  0, 22, 23, 24, 25, 26, 27,  0, 29],
       [30, 31, 32, 33, 34,  0, 36, 37, 38, 39],
       [40, 41,  0, 43, 44, 45, 46, 47, 48,  0],
       [50, 51, 52, 53, 54, 55,  0, 57, 58, 59],
       [60, 61, 62,  0, 64, 65, 66, 67, 68, 69]])

## Using `...` when slicing
(not super important, but might come up)

In [30]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [33]:
arr3[:,:,0]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [34]:
arr3[...,0]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

# <span style="color:#FF6666;font-size:28pt"> Build-a-~bear~ array

## <span style="color:#33FFBB;font-size:16pt"> Native python

**What's the non-numpy way to make a list from [0, 12)**

`[` means that 0 is included (inclusive)  
`)` means that 12 is not included (exclusive)

**What's the non-numpy way to make a list from [5, 12)**

**What's the non-numpy way to write all the multiples of 5 from [1, 100]**

**What's the non-numpy way to count backwards from 10 to 0? (exclusive)**

**What's the non-numpy way to count backwards from 10 to -10? (inclusive)**  
BUT just say the even numbers

**What's the non-numpy way to make a list from [5, 12) BUT...**  
your datapoints should be spaced every 0.1 apart

## <span style="color:#33FFBB;font-size:16pt"> Transferrable numpy

**What's the numpy way to...**
- make a list from [0, 12)
- make a list from [5, 12)
- write all the multiples of 5 from [1, 100]
- count backwards from 10 to 0? (exclusive)
- count backwards from 10 to -10? (inclusive, even only)

In [ ]:
# make an array from [0, 12)



# make an array from [5, 12)



# write all the multiples of 5 from [1, 100]



# count backwards from 10 to 0? (exclusive)



# count backwards from 10 to -10? (inclusive, even only)



# make an array from [5, 12), spaced 0.1 apart




## <span style="color:#33FFBB;font-size:16pt"> Specialized 1D numpy

**Make an array from [5, 12], spaced 0.1 apart**

array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

**Make 1000 points between [5,12]**

In [37]:
np.linspace(5,12,1000)


array([ 5.        ,  5.00700701,  5.01401401,  5.02102102,  5.02802803,
        5.03503504,  5.04204204,  5.04904905,  5.05605606,  5.06306306,
        5.07007007,  5.07707708,  5.08408408,  5.09109109,  5.0980981 ,
        5.10510511,  5.11211211,  5.11911912,  5.12612613,  5.13313313,
        5.14014014,  5.14714715,  5.15415415,  5.16116116,  5.16816817,
        5.17517518,  5.18218218,  5.18918919,  5.1961962 ,  5.2032032 ,
        5.21021021,  5.21721722,  5.22422422,  5.23123123,  5.23823824,
        5.24524525,  5.25225225,  5.25925926,  5.26626627,  5.27327327,
        5.28028028,  5.28728729,  5.29429429,  5.3013013 ,  5.30830831,
        5.31531532,  5.32232232,  5.32932933,  5.33633634,  5.34334334,
        5.35035035,  5.35735736,  5.36436436,  5.37137137,  5.37837838,
        5.38538539,  5.39239239,  5.3993994 ,  5.40640641,  5.41341341,
        5.42042042,  5.42742743,  5.43443443,  5.44144144,  5.44844845,
        5.45545546,  5.46246246,  5.46946947,  5.47647648,  5.48

**Make 28 points between [5,12]**

## <span style="color:#33FFBB;font-size:16pt"> N-D numpy

**Make an array of shape (2,4,5) filled with zeros**

**Make an array of shape (2,4,5) filled with 3's**

In [44]:
np.full((2,4,5),3.)

array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

In [ ]:
np.arange() 
np.linspace() ← use it when you want a constant number of elements
np.ones()
np.zeros()
np.eye() ← identity matrix
np.random.uniform()
np.random.randint()
np.random.normal()
np.random.shuffle()


**Make an identity matrix of shape (10,10)**

## <span style="color:#33FFBB;font-size:16pt"> Numpy.random
**Make an array of shape (2,4,5)...**

In [ ]:
# uniform distribution

# random integers

# gaussian / normal / bell-curve distribution


In [46]:
np.random.randint(0,10, size=(2,4,5))

array([[[4, 2, 7, 9, 7],
        [6, 1, 3, 3, 0],
        [0, 7, 3, 4, 4],
        [7, 7, 0, 4, 2]],

       [[0, 1, 5, 6, 0],
        [3, 8, 4, 7, 6],
        [7, 1, 1, 4, 6],
        [5, 7, 8, 0, 9]]])

In [48]:
np.random.normal(size=(2,4,5))

array([[[-1.12634622,  0.50728687, -0.6085548 ,  1.78579591,
          0.2530732 ],
        [-1.69185586, -0.33585146, -0.39505839,  1.43157752,
         -0.82713698],
        [-0.33490235,  2.29848955, -0.42184302, -0.67656005,
         -1.15005974],
        [ 1.36522669,  0.98211725, -0.22249088, -1.04398848,
         -0.12047753]],

       [[-1.16866281, -0.84595533,  0.11719186, -0.15684445,
         -1.57481827],
        [-0.3591948 ,  0.79500964, -1.92389457, -0.40248653,
          0.93536903],
        [-0.60475717, -0.67604993,  0.16430284,  1.75358432,
          0.06120805],
        [ 0.67373851, -0.06145951,  2.07576974,  0.19357269,
          1.18160476]]])

**Shuffle**

In [49]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [50]:
arr.cumsum()

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415], dtype=int32)

In [55]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
[
    [
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]
    ]
]

In [59]:
arr3.sum(axis=0),arr3.sum(axis=0).shape

(array([[14, 16, 18],
        [20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]),
 (4, 3))

In [60]:
arr3.sum(axis=1), arr3.sum(axis=1).shape

(array([[22, 26, 30],
        [70, 74, 78]]),
 (2, 3))

In [61]:
arr3.sum(axis=2), arr3.sum(axis=2).shape

(array([[ 6, 15, 24, 33],
        [42, 51, 60, 69]]),
 (2, 4))

# <span style="color:#FF6666;font-size:28pt"> Array operations </span>
    
## <span style="color:#33FFBB;font-size:16pt"> Basic functions
arr.sum()  
arr.prod()  
arr.max()  
arr.mean()  
arr.median()  
arr.mode()  
arr.min()  
arr.std()  
...

In [ ]:
arr.sum()

In [51]:
arr.sum(axis=0)

array([210, 217, 224, 231, 238, 245, 252, 259, 266, 273])

In [52]:
arr.sum(axis=1)

array([ 45, 145, 245, 345, 445, 545, 645])

## <span style="color:#33FFBB;font-size:16pt"> Cumulative across one axis
arr.cumsum()  
arr.cumprod()


## <span style="color:#33FFBB;font-size:16pt"> Difference
np.diff(arr)

*copy vs deepcopy*

In [63]:
a = [5,8,-10]
b = a

b[0] = 4
b

[4, 8, -10]

In [64]:
a

[4, 8, -10]