In [1]:
a = [1, 2, 3]

In [2]:
a_list = [a, 'b', 'c']

In [3]:
b_list = [1, 2, a]

In [4]:
a_list

[[1, 2, 3], 'b', 'c']

In [5]:
b_list

[1, 2, [1, 2, 3]]

In [6]:
a_list[0]

[1, 2, 3]

In [7]:
a_list[0][0] = 10

In [8]:
a_list

[[10, 2, 3], 'b', 'c']

In [9]:
b_list

[1, 2, [10, 2, 3]]

In [11]:
c_list = list(a_list)

In [12]:
c_list

[[10, 2, 3], 'b', 'c']

In [13]:
c_list[0][1] = 20

In [14]:
a_list

[[10, 20, 3], 'b', 'c']

In [16]:
from copy import deepcopy

In [17]:
d_list = deepcopy(a_list)

In [18]:
d_list

[[10, 20, 3], 'b', 'c']

In [19]:
a_list

[[10, 20, 3], 'b', 'c']

In [21]:
d_list[0][2] = 30

In [22]:
d_list

[[10, 20, 30], 'b', 'c']

In [23]:
a_list

[[10, 20, 3], 'b', 'c']

In [24]:
import numpy as np

In [32]:
np.array([[1, 2, 3], 
          [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.array([
        [
            [1, 2], 
            [2, 3],
            [4, 5]
        ],
        [
            [4, 5],
            [6, 7],
            [8, 9]
        ]
    ])

array([[[1, 2],
        [2, 3],
        [4, 5]],

       [[4, 5],
        [6, 7],
        [8, 9]]])

In [42]:
np.array([1, 2, 3]).shape

(3,)

In [41]:
np.array(0).shape

()

In [51]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.ones([5, 2], dtype=int) * 3

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [53]:
np.zeros([5, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [64]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.linspace(10, 100, 11, dtype=int)

array([ 10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [71]:
np.logspace(2, 3, base=2)

array([4.        , 4.05698555, 4.11478293, 4.17340372, 4.23285965,
       4.2931626 , 4.35432466, 4.41635805, 4.4792752 , 4.54308869,
       4.60781129, 4.67345595, 4.74003581, 4.8075642 , 4.87605462,
       4.94552078, 5.01597658, 5.08743612, 5.15991371, 5.23342383,
       5.30798122, 5.38360077, 5.46029763, 5.53808714, 5.61698488,
       5.69700662, 5.77816838, 5.8604864 , 5.94397716, 6.02865736,
       6.11454394, 6.2016541 , 6.29000526, 6.37961511, 6.47050158,
       6.56268285, 6.65617737, 6.75100385, 6.84718126, 6.94472885,
       7.04366615, 7.14401294, 7.24578931, 7.34901563, 7.45371255,
       7.55990103, 7.6676023 , 7.77683793, 7.88762977, 8.        ])

In [72]:
2**np.linspace(2, 3)

array([4.        , 4.05698555, 4.11478293, 4.17340372, 4.23285965,
       4.2931626 , 4.35432466, 4.41635805, 4.4792752 , 4.54308869,
       4.60781129, 4.67345595, 4.74003581, 4.8075642 , 4.87605462,
       4.94552078, 5.01597658, 5.08743612, 5.15991371, 5.23342383,
       5.30798122, 5.38360077, 5.46029763, 5.53808714, 5.61698488,
       5.69700662, 5.77816838, 5.8604864 , 5.94397716, 6.02865736,
       6.11454394, 6.2016541 , 6.29000526, 6.37961511, 6.47050158,
       6.56268285, 6.65617737, 6.75100385, 6.84718126, 6.94472885,
       7.04366615, 7.14401294, 7.24578931, 7.34901563, 7.45371255,
       7.55990103, 7.6676023 , 7.77683793, 7.88762977, 8.        ])

In [75]:
a = np.array([[1, 3, 4],
              [4, 5, 6]])
a

array([[1, 3, 4],
       [4, 5, 6]])

In [77]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [78]:
a + b

array([[11, 23, 34],
       [44, 55, 66]])

In [79]:
a - b

array([[ -9, -17, -26],
       [-36, -45, -54]])

In [80]:
a * b

array([[ 10,  60, 120],
       [160, 250, 360]])

In [81]:
a / b

array([[0.1       , 0.15      , 0.13333333],
       [0.1       , 0.1       , 0.1       ]])

In [82]:
5 * a

array([[ 5, 15, 20],
       [20, 25, 30]])

In [84]:
np.matmul(a, b.T)

array([[190, 430],
       [320, 770]])

In [85]:
np.dot(a, b.T)

array([[190, 430],
       [320, 770]])

In [88]:
a.sum()

23

In [89]:
a.cumsum()

array([ 1,  4,  8, 12, 17, 23])

In [90]:
a.prod()

1440

In [91]:
a.cumprod()

array([   1,    3,   12,   48,  240, 1440])

In [93]:
np.diff(a)

array([[2, 1],
       [1, 1]])

In [94]:
a

array([[1, 3, 4],
       [4, 5, 6]])

In [96]:
np.diff(a, axis=0)

array([[3, 2, 2]])

In [97]:
a.sum(axis=0)

array([ 5,  8, 10])

In [98]:
a.sum(axis=1)

array([ 8, 15])

In [99]:
c = np.arange(1, 51).reshape((10, 5))

In [100]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [101]:
c[0, 0]

1

In [102]:
c[0, 1]

2

In [103]:
c[-1, -2]

49

In [104]:
c[0]

array([1, 2, 3, 4, 5])

In [105]:
c[-1]

array([46, 47, 48, 49, 50])

In [107]:
c[:,-1]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [108]:
c[:, 0]

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [110]:
c[1:5, 3]

array([ 9, 14, 19, 24])

In [112]:
c[2, ::2] = 20

In [115]:
len(c)

10

In [116]:
a.shape

(2, 3)

In [117]:
b.shape

(2, 3)

In [118]:
c.shape

(10, 5)

In [119]:
a + b

array([[11, 23, 34],
       [44, 55, 66]])

In [120]:
(a + b) * 4 

array([[ 44,  92, 136],
       [176, 220, 264]])

In [121]:
a + c

ValueError: operands could not be broadcast together with shapes (2,3) (10,5) 

In [122]:
d = np.array([1, 2, 3, 4, 5])

In [123]:
d

array([1, 2, 3, 4, 5])

In [124]:
a + d

ValueError: operands could not be broadcast together with shapes (2,3) (5,) 

In [125]:
c + d

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [21, 14, 23, 18, 25],
       [17, 19, 21, 23, 25],
       [22, 24, 26, 28, 30],
       [27, 29, 31, 33, 35],
       [32, 34, 36, 38, 40],
       [37, 39, 41, 43, 45],
       [42, 44, 46, 48, 50],
       [47, 49, 51, 53, 55]])

In [126]:
c.shape

(10, 5)

In [127]:
e = np.ones((2, 5))

(5, 3, 2)
(3, 2) -> (1, 3, 2) -> (5, 3, 2)

(5, 3, 2)
(5, 3, 1) -> np.newaxis or None

In [129]:
mat1 = np.ones((5, 3, 2))
mat2 = np.ones((5, 3))

In [132]:
(mat1 + mat2[:, :, np.newaxis]).shape

(5, 3, 2)

In [133]:
(mat1 + mat2[:, :, None]).shape

(5, 3, 2)

(5, 1, 6) -> (5, 2, 6)
(1, 2, 1) -> (5, 2, 6)

In [134]:
(np.ones((5, 1, 6)) + np.ones((1, 2, 1))).shape

(5, 2, 6)

In [135]:
mat1.shape

(5, 3, 2)

In [137]:
mat1[:, :, 0]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [138]:
mat1[..., 0]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
mat1[1, ..., 0]

array([1., 1., 1.])

In [164]:
a

array([[1, 3, 4],
       [4, 5, 6]])

In [165]:
a > 3

array([[False, False,  True],
       [ True,  True,  True]])

In [142]:
a[a > 3]

array([4, 4, 5, 6])

In [147]:
c[[2, 3, 4], [0, 1, 2]]

array([20, 17, 23])

In [162]:
c[-2:10]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [163]:
c[5:-1]

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [166]:
c[-2:8]

array([], shape=(0, 5), dtype=int64)

In [149]:
np.random.random()

0.8101368131480211

In [153]:
rng = np.random.default_rng(seed=42)

In [154]:
rng.random((5, 3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363],
       [0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 ]])

In [161]:
rng.integers(5, 10, size=(10, 2))

array([[9, 5],
       [9, 9],
       [6, 8],
       [5, 8],
       [8, 6],
       [5, 9],
       [7, 9],
       [8, 8],
       [8, 5],
       [6, 7]])

In [167]:
rng.normal()

0.36544406436407834

In [172]:
rng.choice([1, 2, 3, 4, 5], size=10)

array([3, 4, 1, 3, 1, 4, 3, 2, 2, 3])

In [173]:
a_list

[[10, 20, 3], 'b', 'c']

In [174]:
rng.shuffle(a_list)

In [175]:
a_list

['b', [10, 20, 3], 'c']

In [176]:
rng.permutation(a_list)

/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


array(['c', 'b', list([10, 20, 3])], dtype=object)

In [177]:
a_list

['b', [10, 20, 3], 'c']

In [178]:
import pandas as pd

In [187]:
s1 = pd.Series([1, 2, 3], index=list('abc'))

In [188]:
s2 = pd.Series({
    'f': 10,
    'g': 11,
    'h': 12,
    'i': 13,
    'j': 14
})

In [186]:
pd.Series(5, index=list('bcd'))

b    5
c    5
d    5
dtype: int64

In [191]:
s2[2]

12

In [193]:
s2['f']

10

In [194]:
s2[::2]

f    10
h    12
j    14
dtype: int64

In [195]:
s2[:3]

f    10
g    11
h    12
dtype: int64

In [196]:
s2.dtype

dtype('int64')

In [197]:
s2[s2>11]

h    12
i    13
j    14
dtype: int64

In [198]:
s2.shape

(5,)

In [200]:
np.exp(s2)

f    2.202647e+04
g    5.987414e+04
h    1.627548e+05
i    4.424134e+05
j    1.202604e+06
dtype: float64