In [1]:
import numpy as np

In [6]:
arr = np.array([[1,2,3],[4,5,6]]) #2d array
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(2, 3)

In [2]:
matrix = np.array([
    [
        [1,2],
        [2,3],
        [4,5]
    ],
    [
        [4,5],
        [6,7],
        [8,9]
    ]
])
display(matrix)
display(matrix.shape)

array([[[1, 2],
        [2, 3],
        [4, 5]],

       [[4, 5],
        [6, 7],
        [8, 9]]])

(2, 3, 2)

In [16]:
vec = np.array([1,2,3]) #vector : 1d array
display(vec)
display(vec.shape)

array([1, 2, 3])

(3,)

In [17]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
3 * np.ones([5,2])

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [24]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.arange(5,10, 0.5) #unlike range(), the step can be float

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [29]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [31]:
np.linspace(10,100,11, dtype=int)

array([ 10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [ ]:
np.logspace(2,3) #10^2 to 10^3 you can change the base as well

In [32]:
10**np.linspace(2,3) == np.logspace(2,3)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [34]:
a = np.array([[1,3,4],[4,5,6]])
display(a)
display(a.shape)

array([[1, 3, 4],
       [4, 5, 6]])

(2, 3)

In [36]:
b = np.array([[10,20,30],[40,50,60]])
display(b)
display(b.shape)

array([[10, 20, 30],
       [40, 50, 60]])

(2, 3)

In [37]:
a + b

array([[11, 23, 34],
       [44, 55, 66]])

In [38]:
a - b

array([[ -9, -17, -26],
       [-36, -45, -54]])

In [39]:
a * b

array([[ 10,  60, 120],
       [160, 250, 360]])

In [40]:
a / b

array([[0.1       , 0.15      , 0.13333333],
       [0.1       , 0.1       , 0.1       ]])

In [41]:
5 *a

array([[ 5, 15, 20],
       [20, 25, 30]])

In [43]:
np.matmul(a,b) #error becuase of wrong dimensions

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [44]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [46]:
a.sum()

23

In [47]:
a.cumsum()

array([ 1,  4,  8, 12, 17, 23], dtype=int32)

In [48]:
a.prod()

1440

In [49]:
a.cumprod()

array([   1,    3,   12,   48,  240, 1440], dtype=int32)

In [51]:
display(a)
np.diff(a) #3-1 , 4-3 ....

array([[1, 3, 4],
       [4, 5, 6]])

array([[2, 1],
       [1, 1]])

In [52]:
np.diff(a, axis=0) #4-1, 5-3 ...

array([[3, 2, 2]])

In [234]:
display(a)
a.sum(axis=0)

array([[1, 3, 4],
       [4, 5, 6]])

array([ 5,  8, 10])

In [54]:
a.sum(axis=1)

array([ 8, 15])

In [8]:
c = np.arange(1,51).reshape((10,5))
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [59]:
c[0, 0] , c[0, 1] , c[-1,-2]

(1, 2, 49)

In [60]:
c[0] #first row

array([1, 2, 3, 4, 5])

In [61]:
c[:,-1] #colon means 'everything in this axis'

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [62]:
c[:,0]

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [64]:
c[1:5,3] #values from row 1 to 4, then column 3

array([ 9, 14, 19, 24])

In [65]:
c[2, ::2] 

array([11, 13, 15])

In [66]:
len(c)

10

In [9]:
d = np.array([1,2,3,4,5])
display(d)
display(c)
display(d.shape, c.shape)

array([1, 2, 3, 4, 5])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

(5,)

(10, 5)

In [69]:
c + d #broadcasting, added d to each row of c

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20],
       [17, 19, 21, 23, 25],
       [22, 24, 26, 28, 30],
       [27, 29, 31, 33, 35],
       [32, 34, 36, 38, 40],
       [37, 39, 41, 43, 45],
       [42, 44, 46, 48, 50],
       [47, 49, 51, 53, 55]])

In [73]:
mat1 = np.ones((5,3,2))
mat2 = np.ones((5,3))
mat1, mat2

(array([[[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [72]:
mat1 + mat2 #error

ValueError: operands could not be broadcast together with shapes (5,3,2) (5,3) 

In [74]:
(mat1 + mat2[:,:, None]).shape #now possible by adding an axis to mat2

(5, 3, 2)

In [ ]:
(5,1,6) --> (5,2,6)
(1,2,1) --> (5,2,6)

In [75]:
(np.ones((5,1,6)) + np.ones((1,2,1))).shape

(5, 2, 6)

In [76]:
mat1

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [77]:
a

array([[1, 3, 4],
       [4, 5, 6]])

In [78]:
a > 3

array([[False, False,  True],
       [ True,  True,  True]])

In [79]:
a[a>3] #returns true values

array([4, 4, 5, 6])

In [80]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [83]:
c[[2,3,4],[0,1,2]] #row2 get 0 column, row3 get column 1

array([11, 17, 23])

In [85]:
rng = np.random.default_rng()

In [87]:
rng.random()

0.6570863396910458

In [89]:
rng.random((5,3)) #returns 5x3 matrix w random values from 0 to 1

array([[0.52021028, 0.08902701, 0.37342849],
       [0.50746357, 0.61729966, 0.75419924],
       [0.57158235, 0.64588998, 0.27287148],
       [0.68814124, 0.78502926, 0.94201414],
       [0.87756969, 0.50685967, 0.45866624]])

In [121]:
rng.integers(5,10)

7

In [123]:
rng.integers(5,10, size=(10,2)) #creates 10x2 array w values from 5 to 10

array([[6, 6],
       [9, 9],
       [5, 7],
       [5, 7],
       [8, 7],
       [7, 7],
       [6, 5],
       [7, 5],
       [7, 8],
       [5, 6]], dtype=int64)

In [135]:
rng.normal()

-0.9623190419650293

In [181]:
rng.choice([1,2,3,4], size = 2)

array([3, 4])

In [194]:
a_list = [1,2,3,4,5,6]
np.random.shuffle(a_list) #modifies the list directly
a_list

[2, 6, 5, 3, 4, 1]

In [233]:
display(np.random.permutation(a_list)) #does not modify original list
display(a_list)

array([3, 6, 2, 1, 5, 4])

[2, 6, 5, 3, 4, 1]