In [1]:
import numpy as np
import torch

In [2]:
#bernoulli likelihood
np.random.seed(1)

#generate bern samples

x = np.random.binomial(n=1, p=0.75, size=100)
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [3]:
np.mean(x)

0.77

In [5]:
x = torch.tensor(x).type(torch.FloatTensor)
x.requires_grad = True 
x

<ipython-input-5-7107f11dbf31>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x).type(torch.FloatTensor)


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
        1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
        1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
        1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
        1., 0., 1., 1., 1., 1., 0., 1., 1., 1.], requires_grad=True)

In [6]:
def neg_loglik_bernoulli(x, p):
    """
    x,p should be torch tensors
    """
    return -torch.sum(torch.log(x*p + (1-x)*(1-p))) #logging the pmf of bern and sum then negative because we are maximizing


In [12]:
#initialize guess for p to use grad descent
torch.manual_seed(4)
p = torch.rand(1, requires_grad=True)
print('p = ', p.data.numpy())

#grad descent, minimize negative loglikelihood
learning_rate = 0.0001


#training loop
for t in range(500):
    neg_loglik = neg_loglik_bernoulli(x, p) #forward pass
    neg_loglik.backward() #calculates the gradients
    
    if t%100 == 0:
        print('neg-loglik = ', neg_loglik.data.numpy().round(2), 'p =', p.data.numpy().round(2), 'dL/dp =', p.grad.data.numpy().round(4))
        
    #actual gradient desc
    p.data -= learning_rate*p.grad.data
    p.grad.data.zero_() #resets gradients for each epoch
    

p =  [0.5596386]
neg-loglik =  63.56 p = [0.56] dL/dp = [-85.359]
neg-loglik =  53.93 p = [0.77] dL/dp = [-0.6065]
neg-loglik =  53.93 p = [0.77] dL/dp = [-0.0018]
neg-loglik =  53.93 p = [0.77] dL/dp = [-0.0003]
neg-loglik =  53.93 p = [0.77] dL/dp = [-0.0003]


### Exponential Likelihood

In [16]:
x = [3, 1.5, 2.1] #from lecture slides
x = torch.tensor(x).type(torch.FloatTensor)
x.requires_grad = True
x

tensor([3.0000, 1.5000, 2.1000], requires_grad=True)

In [18]:
def neg_loglik_exponential(x, beta):
    return -torch.sum(torch.log(beta*torch.exp(-x*beta)))

In [29]:
#initialize random guess for beta
torch.manual_seed(5)
beta = torch.rand(1, requires_grad=True)
print('beta =', beta.data.numpy())

#grad desc, minimize negative loglikelihood

learning_rate = 0.01
for t in range(1000):
    
    neg_loglik = neg_loglik_exponential(x, beta)
    neg_loglik.backward() #backward pass -> calc the gradient dL/dbeta
    
    if t%100 == 0:
        print('neg-loglik = ', neg_loglik.data.numpy().round(2), 'beta =', beta.data.numpy().round(4), 'dL/dp =', beta.grad.data.numpy().round(4))
    
    beta.data -= learning_rate * beta.grad.data
    beta.grad.data.zero_()

beta = [0.8302519]
neg-loglik =  6.04 beta = [0.8303] dL/dp = [2.9866]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
neg-loglik =  5.37 beta = [0.4545] dL/dp = [0.]
