## Notebook 4C: Seatwork

<b>Instructions:</b> Submit your answers by <b>LT</b>.

LT Number: 10

Names:\
&emsp;Janica Lae Batang\
&emsp;Mary Honeylie Buitre\
&emsp;Paolo Jose de Guzman\
&emsp;John Francis Gacal\
&emsp;Vincent John Rivera

### Q1.

#### (a) Compute the eigenvalues and eigenvector of the matrix

\begin{align}
    A = \begin{bmatrix}
            6 & 16 \\
            -1 & -4
        \end{bmatrix}
\end{align}

#### Answer:
\begin{align}
\text{det}(A - \lambda I) = 
\text{det}\bigg(
\begin{bmatrix}
6-\lambda & 16 \\
-1 & -4-\lambda
\end{bmatrix}
\bigg) = 0
\end{align}
\
Solution:
\begin{align}
\lambda^2 - 2 \lambda - 8 = 0
\end{align}

\
\begin{align}
    \lambda_1 = 4 \quad &, \quad
    v_1 = \begin{bmatrix}
            1\\
            -\frac{1}{8}
        \end{bmatrix}
\end{align}

\begin{align}
    \lambda_2 = -2 \quad &, \quad
    v_2 = \begin{bmatrix}
            1\\
            -\frac{1}{2}
        \end{bmatrix}
\end{align}

In [4]:
#Checking answers through normalization
v1 = np.array([[1],
               [-1/8]])
norm_v1 = np.sqrt(v1[0]**2 + v1[1]**2)
normal_v1 = v1 / norm_v1
print('v1\n',normal_v1,'\n')

v2 = np.array([[1],
               [-1/2]])
norm_v2 = np.sqrt(v1[0]**2 + v1[1]**2)
normal_v2 = v2 / norm_v2
print('v2\n',normal_v2)

v1
 [[ 0.99227788]
 [-0.12403473]] 

v2
 [[ 0.99227788]
 [-0.49613894]]


In [1]:
# You may use numpy to check your answer

import numpy as np

A = np.array([[6, 16],
             [-1, -4]])
print(np.linalg.eig(A))

(array([ 4., -2.]), array([[ 0.99227788, -0.89442719],
       [-0.12403473,  0.4472136 ]]))


#### (b) Compute the eigenvalues and eigenvector of the matrix

\begin{align}
    A = \begin{bmatrix}
            4 & 0 & 1 \\
            -1 & -6 & -2 \\
            5 & 0 & 0
        \end{bmatrix}
\end{align}

Once you have set up the characteristic polynomial, you can use the Newton-Raphson method to solve for all 3 roots.

In [36]:
# Insert Newton-Raphson method here
def f(x):
    return -x**3 - 2*x**2 + 29*x + 30

def df(x):
    return -3*x**2 - 4*x + 29

x_k = 1
print('Initial guess of x_k =', x_k)
for k in range(6):
    print('k = %d --' %k, '-- x_k[0] = %.4f --' %x_k, '-- f(x_k) = %.4f' %f(x_k))
    x_k = x_k - f(x_k)/df(x_k)
    
print('\n')
x_k = 2  
print('Initial guess of x_k =', x_k)
for k in range(6):
    print('k = %d --' %k, '-- x_k[0] = %.4f --' %x_k, '-- f(x_k) = %.4f' %f(x_k))
    x_k = x_k - f(x_k)/df(x_k)    

print('\n')
x_k = 3
print('Initial guess of x_k =', x_k)
for k in range(10):
    print('k = %d --' %k, '-- x_k[0] = %.4f --' %x_k, '-- f(x_k) = %.4f' %f(x_k))
    x_k = x_k - f(x_k)/df(x_k) 

Initial guess of x_k = 1
k = 0 -- -- x_k[0] = 1.0000 -- -- f(x_k) = 56.0000
k = 1 -- -- x_k[0] = -1.5455 -- -- f(x_k) = -15.9038
k = 2 -- -- x_k[0] = -0.9778 -- -- f(x_k) = 0.6666
k = 3 -- -- x_k[0] = -1.0000 -- -- f(x_k) = 0.0005
k = 4 -- -- x_k[0] = -1.0000 -- -- f(x_k) = 0.0000
k = 5 -- -- x_k[0] = -1.0000 -- -- f(x_k) = 0.0000


Initial guess of x_k = 2
k = 0 -- -- x_k[0] = 2.0000 -- -- f(x_k) = 72.0000
k = 1 -- -- x_k[0] = -6.0000 -- -- f(x_k) = 0.0000
k = 2 -- -- x_k[0] = -6.0000 -- -- f(x_k) = 0.0000
k = 3 -- -- x_k[0] = -6.0000 -- -- f(x_k) = 0.0000
k = 4 -- -- x_k[0] = -6.0000 -- -- f(x_k) = 0.0000
k = 5 -- -- x_k[0] = -6.0000 -- -- f(x_k) = 0.0000


Initial guess of x_k = 3
k = 0 -- -- x_k[0] = 3.0000 -- -- f(x_k) = 72.0000
k = 1 -- -- x_k[0] = 10.2000 -- -- f(x_k) = -943.4880
k = 2 -- -- x_k[0] = 7.2873 -- -- f(x_k) = -251.8649
k = 3 -- -- x_k[0] = 5.7078 -- -- f(x_k) = -55.5878
k = 4 -- -- x_k[0] = 5.1008 -- -- f(x_k) = -6.8237
k = 5 -- -- x_k[0] = 5.0025 -- -- f(x_k) = -0.

#### Answer:

\begin{align}
\text{det}(A - \lambda I) = 
\text{det}\Bigg(
\begin{bmatrix}
4-\lambda & 0 & 1 \\
-1 & -6-\lambda & -2 \\
5 & 0 & -\lambda
\end{bmatrix}
\Bigg) = 0
\end{align}


\begin{align}
\begin{vmatrix}
4-\lambda & 0 & 1 \\
-1 & -6-\lambda & -2 \\
5 & 0 & -\lambda
\end{vmatrix}
= (-6-\lambda)(-1)^{2+2}
\begin{vmatrix}
4-\lambda & 1 \\
5 & -\lambda
\end{vmatrix}
= (-\lambda -6)(\lambda^2 -4\lambda -5)
\end{align}

Solution:
\begin{align}
-\lambda^3-2\lambda^2 + 29\lambda +30 = 0
\end{align}


\begin{align}
    \lambda_1 = -1 \quad &, \quad
    v_1 = \begin{bmatrix}
            1\\
            \frac{9}{5}\\
            -5
        \end{bmatrix}
\end{align}

\begin{align}
    \lambda_2 = -6 \quad &, \quad
    v_2 = \begin{bmatrix}
            0\\
            1\\
            0
        \end{bmatrix}
\end{align}

\begin{align}
    \lambda_3 = 5 \quad &, \quad
    v_3 = \begin{bmatrix}
            1\\
            -\frac{3}{11}\\
            1
        \end{bmatrix}
\end{align}

In [7]:
#Checking answers through normalization
v1 = np.array([[1],
               [9/5],
               [-5]])
norm_v1 = np.sqrt(v1[0]**2 + v1[1]**2 + v1[2]**2)
normal_v1 = v1 / norm_v1
print('v1\n',normal_v1,'\n')

v2 = np.array([[0],
               [1],
               [0]])
norm_v2 = np.sqrt(v2[0]**2 + v2[1]**2 + v2[2]**2)
normal_v2 = v2 / norm_v2
print('v2\n',normal_v2,'\n')

v3 = np.array([[1],
               [-3/11],
               [1]])
norm_v3 = np.sqrt(v3[0]**2 + v3[1]**2 + v3[2]**2)
normal_v3 = v3 / norm_v3
print('v3\n',normal_v3)

v1
 [[ 0.18493168]
 [ 0.33287702]
 [-0.9246584 ]] 

v2
 [[0.]
 [1.]
 [0.]] 

v3
 [[ 0.69431384]
 [-0.18935832]
 [ 0.69431384]]


In [24]:
# You may use numpy to check your answer
import numpy as np

A = np.array([[4, 0, 1],
             [-1, -6, -2],
             [5, 0, 0]])
print(np.linalg.eig(A))

(array([-6.,  5., -1.]), array([[ 0.        ,  0.69431384, -0.18493168],
       [ 1.        , -0.18935832, -0.33287702],
       [ 0.        ,  0.69431384,  0.9246584 ]]))
