## Notebook 4C: Seatwork 2

<b>Instructions:</b> Submit your answers by <b>LT</b>.

## Eigenvalue Application: Markov Chains

A <b><i>Markov Chain</i></b> is a system that has $n$ possible states and passes through a series of transitions from one state to another.

The probability of a transition from state $i$ to state $j$ is given by $a_{ij}$ where

\begin{align}
    0 \leq a_{ij} \leq 1
\end{align}

\begin{align}
    \sum_{i = 1}^{n} a_{ij} = 1
\end{align}

Consider the following <b><i>stock market state model</i></b>:

<img src = "stockmarket.png" width = "300"/>

The model is typically represented as a <b><i>probability transition matrix</i></b>, given by

\begin{align}
    A = \begin{bmatrix}
        0.975 & 0.3 & 0.02\\
        0.02 & 0.5 & 0.40\\
        0.005 & 0.2 & 0.58
    \end{bmatrix}
\end{align}

Note that each column contains the probabilities of moving to state $i$ given that you are in state $j$, such that

- State $1$ corresponds to being in the Bull Market state
- State $2$ corresponds to being in the Bear Market state
- State $3$ corresponds to being in the Stagnant Market state

Some examples:
- Given that we are in a Bull Market (column 1), the probability that in the next time step we stay in a Bull Market is 97.5%.
- Given that we are in a Stagnant Market (column 3), the probability that in the next time step we enter a Bear Market is 40%.
- And so on...

Given $A$, let $x_i^{(k)}$ denote the probability that the system is in state $i$ after transition $k$:

\begin{align}
    x^{(k)} = \begin{bmatrix}
                x_1^{(k)}\\
                x_2^{(k)}\\
                x_3^{(k)}
            \end{bmatrix}
\end{align}

If the initial <b><i>probability distribution vector</i></b> is $x^{(0)}$, then the probability distribution vector after $k$ steps is

\begin{align}
    x^{(k)} = Ax^{(k-1)} = A^kx^{(0)}
\end{align}

The long-term behavior of the system is therefore determined by the value of

\begin{align}
    \lim_{k \rightarrow \infty} A^k
\end{align}

#### Q1.

Suppose that the stock market is initially in a Bull Market.

\begin{align}
    x^{(0)} = \begin{bmatrix}
                1\\
                0\\
                0\\
            \end{bmatrix}
\end{align}

What is the probability distribution vector after three steps?

In [1]:
import numpy as np
from sympy import *

In [62]:
# Insert code here
A = np.array([[0.975,0.3,0.02],[0.02,0.5,0.4],[0.005,0.2,0.58]])
x_0 = np.matrix('0.7; 0.2; 0.1')

x_3 = np.matmul(np.linalg.matrix_power(A, 3),x_0)
x_3

matrix([[0.79637941],
        [0.11908435],
        [0.08453624]])

matrix([[0.88495575],
        [0.07079646],
        [0.04424779]])

#### Q2.

What is the long-term value of the probability distribution vector? (i.e. $\lim_{k \rightarrow \infty} x^{(k)}$)

In [56]:
# Insert code here


x_k = np.matmul(np.linalg.matrix_power(A, 1000000),x_0)
display(x_k)


matrix([[0.88495575],
        [0.07079646],
        [0.04424779]])

In [63]:
lim_D = np.zeros((3,3))
for i,j in zip([1,0,0],[0,1,2]):
    lim_D[j,j] = i

    
P_lim_D = np.matmul(vec,lim_D)
P_limD_Pinv = np.matmul(P_lim_D,np.linalg.inv(vec))

np.matmul(P_limD_Pinv,x_0)

matrix([[0.88495575],
        [0.07079646],
        [0.04424779]])

#### Q3.

Does the long-term value of the probability distribution vector depend on the particular starting value $x^{(0)}$?

#### Answer:

to a certain decimal place, it matters.

In [ ]:
# Insert code here

#### Q4.

What is the value of $\lim_{k \rightarrow \infty} A^k$?

In [65]:
# Insert code here

A_k = np.linalg.matrix_power(A,1000)
A_k

array([[0.88495575, 0.88495575, 0.88495575],
       [0.07079646, 0.07079646, 0.07079646],
       [0.04424779, 0.04424779, 0.04424779]])

In [64]:
P_limD_Pinv

array([[0.88495575, 0.88495575, 0.88495575],
       [0.07079646, 0.07079646, 0.07079646],
       [0.04424779, 0.04424779, 0.04424779]])

#### Q5.

Compute the eigenvalues and eigenvectors of $A$. 

In [8]:
# Insert code here

val,vec = np.linalg.eig(A)

display(np.linalg.eig(A))


(array([1.        , 0.80382635, 0.25117365]),
 array([[ 0.99557949,  0.81563112,  0.32258572],
        [ 0.07964636, -0.44036406, -0.8108726 ],
        [ 0.04977897, -0.37526706,  0.48828688]]))

#### Q6.

Explain your answer in <b>Q4</b> in terms of the eigenvalues and eigenvectors.

#### Answer:

(?)

In [ ]:
# Insert code here
A_val_iden = A - val[1]*np.identity(3)
display(A_val_iden)

np.matmul(A_val_iden,np.matrix(vec[:,1]).T)


#### Q7.

Must 1 always be an eigenvalue of the transition matrix of a Markov chain? Why?

#### Answer:

(?)

#### Q8.

A probability distribution vector $x$ is said to be <b><i>stationary</i></b> if $Ax = x$. 

How can you determine such a stationary value $x$ using the eigenvalues and eigenvectors of $A$?

<i>Some Hints</i>:

1) Recall the formal definition of an eigenvalue-eigenvector pair. Can you see its relation to the question being asked?

2) Try solving <b>Q5</b> by hand <u>OR</u> try to understand what `numpy.linalg.eig` does to your eigenvectors.

#### Answer:

(?)

In [86]:
#stationary prob dist vector
print('--x_k--')
display(x_k)

# A*x_k
print('---A*x_k---')
display(np.matmul(A,x_k))

# A*eigenvector
print('---A*eigenvector----')
display(np.matmul(A,np.matrix(vec[:,0]).T))
display(np.matrix(vec[:,0]).T)

--x_k--


matrix([[0.88495575],
        [0.07079646],
        [0.04424779]])

---A*x_k---


matrix([[0.88495575],
        [0.07079646],
        [0.04424779]])

---A*eigenvector----


matrix([[0.99557949],
        [0.07964636],
        [0.04977897]])

matrix([[0.99557949],
        [0.07964636],
        [0.04977897]])

#### Q9.

How can you determine a stationary value $x$ <i>without</i> knowledge of the eigenvalues and eigenvectors of $A$?

#### Answer:

(?)

#### Q10.

Can there be more than one stationary distribution vector for a given Markov chain? If not, why? If so, give an example.

#### Answer:

(?)

In [ ]:
# Insert code here

#### Bonus.

Is it possible for a Markov chain to <b><u>NOT</b></u> have a stationary distribution? If not, why? If so, give an example.

#### Answer:

(?)