## Notebook 4C: Seatwork 2

<b>Instructions:</b> Submit your answers by <b>LT</b>.

## Eigenvalue Application: Markov Chains

A <b><i>Markov Chain</i></b> is a system that has $n$ possible states and passes through a series of transitions from one state to another.

The probability of a transition from state $i$ to state $j$ is given by $a_{ij}$ where

\begin{align}
    0 \leq a_{ij} \leq 1
\end{align}

\begin{align}
    \sum_{i = 1}^{n} a_{ij} = 1
\end{align}

Consider the following <b><i>stock market state model</i></b>:

<img src = "stockmarket.png" width = "300"/>

The model is typically represented as a <b><i>probability transition matrix</i></b>, given by

\begin{align}
    A = \begin{bmatrix}
        0.975 & 0.3 & 0.02\\
        0.02 & 0.5 & 0.40\\
        0.005 & 0.2 & 0.58
    \end{bmatrix}
\end{align}

Note that each column contains the probabilities of moving to state $i$ given that you are in state $j$, such that

- State $1$ corresponds to being in the Bull Market state
- State $2$ corresponds to being in the Bear Market state
- State $3$ corresponds to being in the Stagnant Market state

Some examples:
- Given that we are in a Bull Market (column 1), the probability that in the next time step we stay in a Bull Market is 97.5%.
- Given that we are in a Stagnant Market (column 3), the probability that in the next time step we enter a Bear Market is 40%.
- And so on...

Given $A$, let $x_i^{(k)}$ denote the probability that the system is in state $i$ after transition $k$:

\begin{align}
    x^{(k)} = \begin{bmatrix}
                x_1^{(k)}\\
                x_2^{(k)}\\
                x_3^{(k)}
            \end{bmatrix}
\end{align}

If the initial <b><i>probability distribution vector</i></b> is $x^{(0)}$, then the probability distribution vector after $k$ steps is

\begin{align}
    x^{(k)} = Ax^{(k-1)} = A^kx^{(0)}
\end{align}

The long-term behavior of the system is therefore determined by the value of

\begin{align}
    \lim_{k \rightarrow \infty} A^k
\end{align}

#### Q1.

Suppose that the stock market is initially in a Bull Market.

\begin{align}
    x^{(0)} = \begin{bmatrix}
                1\\
                0\\
                0\\
            \end{bmatrix}
\end{align}

What is the probability distribution vector after three steps?

In [1]:
# Insert code here

import numpy as np

A = np.matrix([[0.975, 0.3, 0.02],
              [0.02, 0.5, 0.4],
              [0.005, 0.2, 0.58]])

x_0 = np.array([1, 0, 0])

x_3 = np.linalg.matrix_power(A, 3).dot(x_0)

print(x_3)

[[0.94249237 0.0395945  0.01791313]]


#### Q2.

What is the long-term value of the probability distribution vector? (i.e. $\lim_{k \rightarrow \infty} x^{(k)}$)

In [3]:
# Insert code here

x_0 = np.array([1, 0, 0])

x_n = np.linalg.matrix_power(A, 100).dot(x_0)
    
print(x_n)

[[0.88495575 0.07079646 0.04424779]]


#### Q3.

Does the long-term value of the probability distribution vector depend on the particular starting value $x^{(0)}$?

#### Answer:

No. (Try different starting values)

In [4]:
# Insert code here
import numpy as np
x_0 = np.array([0, 1, 0])

x_n = np.linalg.matrix_power(A, 100).dot(x_0)
    
print(x_n)

[[0.88495575 0.07079646 0.04424779]]


#### Q4.

What is the value of $\lim_{k \rightarrow \infty} A^k$?

In [63]:
# Insert code here

print(np.linalg.matrix_power(A, 100))

[[0.88495575 0.88495575 0.88495575]
 [0.07079646 0.07079646 0.07079646]
 [0.04424779 0.04424779 0.04424779]]


#### Q5.

Compute the eigenvalues and eigenvectors of $A$. 

In [64]:
# Insert code here

eig_vals, eig_vecs = np.linalg.eig(A)

print(eig_vals)
print(eig_vecs)

#print(eig_vecs[:, 0]/sum(eig_vecs[:, 0]))

[1.         0.80382635 0.25117365]
[[ 0.99557949  0.81563112  0.32258572]
 [ 0.07964636 -0.44036406 -0.8108726 ]
 [ 0.04977897 -0.37526706  0.48828688]]


#### Q6.

Explain your answer in <b>Q4</b> in terms of the eigenvalues and eigenvectors.

#### Answer:

$\lim_{k \rightarrow \infty} A^k = PD^k P^{-1}$

In [14]:
# Insert code here

D_k = eig_vals**100
print(eig_vecs*np.diag(D_k)*np.linalg.inv(eig_vecs))

[[0.88495575 0.88495575 0.88495575]
 [0.07079646 0.07079646 0.07079646]
 [0.04424779 0.04424779 0.04424779]]


#### Q7.

Must 1 always be an eigenvalue of the transition matrix of a Markov chain? Why?

#### Answer:

Yes. In fact, it must also be the largest eigenvalue (in absolute value). Otherwise $\lim_{k \rightarrow \infty} A^k$ would (1) explode and (2) would not be a valid probability transition matrix.

#### Q8.

A probability distribution vector $x$ is said to be <b><i>stationary</i></b> if $Ax = x$. 

How can you determine such a stationary value $x$ using the eigenvalues and eigenvectors of $A$?

<i>Some Hints</i>:

1) Recall the formal definition of an eigenvalue-eigenvector pair. Can you see its relation to the question being asked?

2) Try solving <b>Q5</b> by hand <u>OR</u> try to understand what `numpy.linalg.eig` does to your eigenvectors.

#### Answer:

The eigenvector pair of the eigenvalue $\lambda_1 = 1$ gives the stationary probability distribution vector (when it is scaled to be a valid probability vector).

In [70]:

# Insert code here
eig_vals, eig_vecs = np.linalg.eig(A)

print(eig_vecs[:, 0]/sum(eig_vecs[:, 0]))

[[0.88495575]
 [0.07079646]
 [0.04424779]]


#### Q9.

How can you determine a stationary value $x$ <i>without</i> knowledge of the eigenvalues and eigenvectors of $A$?

#### Answer:

Numerically. Like in <b>Q2</b>.

#### Q10.

Can there be more than one stationary distribution vector for a given Markov chain? If not, why? If so, give an example.

#### Answer:
Yes.

\begin{align}
    A = \begin{bmatrix}
        1 & 0\\
        0 & 1
    \end{bmatrix}
\end{align}

In [9]:
# Insert code here

I = np.matrix([[1, 0],
              [0, 1]])

x = np.array([0.5, 0.5])

print(np.linalg.matrix_power(I, 3).dot(x))

eig_vals, eig_vecs = np.linalg.eig(I)

print(eig_vals)
print(eig_vecs)

[[0.5 0.5]]
[1. 1.]
[[1. 0.]
 [0. 1.]]


#### Bonus.

Is it possible for a Markov chain to <b><u>NOT</b></u> have a stationary distribution? If not, why? If so, give an example.

#### Answer:

Yes, for an infinite state space. Let $S = {1, 2, 3, \ldots}$ and $P(i, i+1) = 1$.